spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: paybridge-kafka:9092

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 8080

# ========================
# JWT CONFIG
# ========================
jwt:
  secret-key: ${JWT_SECRET_KEY}
  ttl-ms: ${JWT_TTL}

# ========================
# INTERNAL SERVICE TOKENS
# ========================
tokens:
  internal-service: ${TOKEN_INTERNAL_SERVICE}
  transaction-service: ${TOKEN_TRANSACTION_SERVICE}
  notification-service: ${TOKEN_NOTIFICATION_SERVICE}

# ========================
# EXTERNAL SERVICE ENDPOINTS
# ========================
services:
  transaction:
    endpoint: ${TRANSACTION_SERVICE_ENDPOINT}
